feat: 3D profile 2.0
MapColonies/catalog-web-app-bff pull request #103
Opened 2022-09-04 16:10 UTC by EllaMartirosyan

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| New feature     | ✔                                                                        |

2022-09-05 05:05 UTC, alebinson requested changes
see my comments

2022-09-05 05:05 UTC, alebinson commented on src/AUTOGENERATED/GraphQLClass.ts
> +    public productStatus?: string;
Should be **not-Nullable and enum**

2022-09-08 03:52 UTC, EllaMartirosyan commented on src/AUTOGENERATED/GraphQLClass.ts
> +    public productStatus?: string;
Fixed in mc-models

2022-09-19 10:32 UTC, alebinson approved these changes
gr8!

2022-09-19 11:09 UTC, merged